# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.0.0-3-g14c6baf
_src_path: git@github.com:elastic/mlops-platform-template
description: OpenAPI based MCP server
include_ml_utils: false
license: MIT
mlflow_version: ''
name: ML ES OpenAPI MCP server
package: ml_rd_mcp
python_version: '3.10'
repository: ml-rnd-mcp
sonarqube_project_key: ''
user: elastic
version: 0.1.0
