# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.0.0-3-g14c6baf
_src_path: git@github.com:elastic/mlops-platform-template
description: OpenAPI based MCP server
include_ml_utils: false
license: MIT
mlflow_version: ''
name: ML ES OpenAPI MCP server
package: elastic_fastmcp
python_version: '3.10'
repository: ml-rnd-mcp
sonarqube_project_key: 'elastic_elastic-fastmcp-server_fbe99cff-82d5-4538-9bd0-f695685b9009'
user: elastic
version: 0.1.0
