name: Pull Template Updates
permissions:
  contents: write
  pull-requests: write
on:
  schedule:
    - cron: "0 0 * * *" # Every day at 12am UTC
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install copier
        run: pipx install copier==9.6.0
      - name: Set SSH key for reading template repository
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.TEMPLATE_SSH_KEY }}
      - name: Retrieve template changes
        id: update
        run: |
          set +e
          OUTPUT=$(copier update --skip-answered --conflict inline 2>&1)
          EXIT_CODE=$?
          set -e

          echo "$OUTPUT"

          # We assume that if EOFError is in the output, there are unanswered questions
          if [[ "$OUTPUT" == *"EOFError"* ]]; then
            echo "has_unanswered_questions=1" >> "$GITHUB_OUTPUT"
            echo "has_changes=1" >> "$GITHUB_OUTPUT"  # if there are unanswered questions, there are changes

            # We need to commit to create a PR
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions@github.com"
            git commit --allow-empty -m "Dummy commit to force PR creation"

            exit 0
          else
            echo "has_unanswered_questions=0" >> "$GITHUB_OUTPUT"
          fi

          git restore --staged .
          echo "has_changes=$(git status --porcelain | wc -l)" >> "$GITHUB_OUTPUT"

          if [ $EXIT_CODE -ne 0 ]; then
            echo "Copier update failed due to an unexpected error."
            exit $EXIT_CODE
          fi
      - name: Create pull request
        if: steps.update.outputs.has_changes != '0'
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          add-paths: .
          commit-message: "Pull template updates"
          branch: copier/update
          delete-branch: true
          branch-suffix: timestamp
          title: New MLOps Template Release
          body: |
            🤖 This is an autogenerated PR.

            [Copier](https://copier.readthedocs.io/en/stable/) has detected a new release in the [MLOps template repository](https://github.com/elastic/mlops-platform-template) that has not been integrated in your repository.

            In order to get the latest improvements in the template, please review the changes and merge this Pull Request.

            ⚠️ There is a chance that the new changes conflict with your local changes. In that case, you will need to
            resolve the conflicts manually.
            1. Checkout the `copier/update` branch from this PR locally in your IDE.
            2. Look for the files with conflicts. Conflicts are marked using the common conflict markers `<<<<<<<`,
              `=======`, and `>>>>>>>`, so you can search any of these markers in your files to find them quickly.
            3. Resolve the conflicts using your IDE UI, commit and push the changes to this PR.

            ❌ We have a pre-commit hook called `check-merge-conflict` to prevent the merge of a PR if there are
            conflicts. Do NOT bypass this check.

            ⚠️ There is a chance new questions have been introduced in the [template questionnaire](https://github.com/elastic/mlops-platform-template?tab=readme-ov-file#2-generate-your-project-cookie).
            In that case, a comment will be added to this PR with additional instructions.

            💡 Tip - If you need it, you can update your repository against the template with `copier update --skip-answered --conflict inline`.
      - name: Print Pull Request information
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
          echo "Pull Request HEAD Sha - ${{ steps.cpr.outputs.pull-request-head-sha }}"
          echo "Pull Request Branch - ${{ steps.cpr.outputs.pull-request-branch }}"
      - name: Comment on PR if questions are unanswered
        if: steps.update.outputs.has_unanswered_questions == '1' && steps.cpr.outputs.pull-request-number
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
          body: |
            ⚠️ Copier found new questions that require manual input.

            Please run `copier update --skip-answered --conflict inline` locally and answer the new questions.
            Then, update this PR.
          edit-mode: replace
          reactions: eyes
